# Generated by Django 5.2.17 on 2026-08-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('demand', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=225)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_distance_naive', models.FloatField(blank=True, null=True)),
                ('total_distance_optimized', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='optimizer.depot')),
            ],
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField()),
                ('delivery_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.deliverypoint')),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='optimizer.routeplan')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.vehicle')),
            ],
        ),
    ]
